const CLUSTER_NAME = "edamame";
const ARCHIVE = "edamame-load-tests";
const SINGLE_UPLOAD_MAX_SIZE = 104857600; // 100 MiB
const MULTIPART_UPLOAD_MAX_SIZE = SINGLE_UPLOAD_MAX_SIZE * 10000;

export {
  CLUSTER_NAME,
  ARCHIVE,
  SINGLE_UPLOAD_MAX_SIZE,
  MULTIPART_UPLOAD_MAX_SIZE
};
